### PR TITLE
Some small changes

### PR DESCRIPTION
**Pull request by LetsMelon**
Hey!

I saw your project on `r/rust` and I think it's a nice project.

The PR changes
- add `.DS_Store` to the `.gitignore`
- delete `flamegraph.svg`

Another thing I noticed is that when I cloned this repo, its size is `72.23 MiB`, which is quite large. Additionally, I would rename the folder `btr` to something more appropriate, like `test_files`, because I had to look through your code to understand the purpose of the directory.

### CODE REVIEW

**Comment by LetsMelon** [comment]
And another thing are the two worklow files in `src/.github/workflows`. Does github really run them? Because it's not quit clear from the official [documentation](https://docs.github.com/en/actions/using-workflows/about-workflows)

> GitHub Actions uses YAML syntax to define the workflow. Each workflow is stored as a separate YAML file in your code repository, in a directory named .github/workflows.

**Review by LetsMelon — COMMENTED** [review]
This commit is not really necessary anymore because https://github.com/gabrieldemian/vincenzo/commit/b9d1b1110481ae9eb0665be5f41f29be7aebd067 deletes `framegraph.svg`.

**Comment by gabrieldemian** [comment]
> Hey!
> 
> I saw your project on `r/rust` and I think it's a nice project.
> 
> The PR changes
> 
> * add `.DS_Store` to the `.gitignore`
> * delete `flamegraph.svg`
> 
> Another thing I noticed is that when I cloned this repo, its size is `72.23 MiB`, which is quite large. Additionally, I would rename the folder `btr` to something more appropriate, like `test_files`, because I had to look through your code to understand the purpose of the directory.

Hello! Thanks for the contribution. I agree that we should have a better name like `test_files`. Do you want to include this in your PR?

**Comment by gabrieldemian** [comment]
> And another thing are the two worklow files in `src/.github/workflows`. Does github really run them? Because it's not quit clear from the official [documentation](https://docs.github.com/en/actions/using-workflows/about-workflows)
> 
> > GitHub Actions uses YAML syntax to define the workflow. Each workflow is stored as a separate YAML file in your code repository, in a directory named .github/workflows.

yes, one workflow will run automated tests when pushing code, the other one will compile the binary to multiple different OS

**Review by gabrieldemian — APPROVED** [review]

**Comment by gabrieldemian** [comment]
Also, I will open some good first-issues, if you're interested I would love to have some contributions!

**Comment by LetsMelon** [comment]
> > And another thing are the two worklow files in `src/.github/workflows`. Does github really run them? Because it's not quit clear from the official [documentation](https://docs.github.com/en/actions/using-workflows/about-workflows)
> > > GitHub Actions uses YAML syntax to define the workflow. Each workflow is stored as a separate YAML file in your code repository, in a directory named .github/workflows.
> 
> yes, one workflow will run automated tests when pushing code, the other one will compile the binary to multiple different OS

You have duplicated your workflow files. They are present in both `./src/.github/workflows` and `./.github/workflows`. However, GitHub only recognizes the configuration from `./.github/workflows`. If you go to the "Actions" tab, you'll notice only two workflows listed instead of four.

To print all `.yml` files to the terminal:

```sh
$ find . | grep "\.yml$"
./.github/workflows/release.yml
./.github/workflows/build.yml
./src/.github/workflows/release.yml
./src/.github/workflows/build.yml
```

**Comment by LetsMelon** [comment]
> > Hey!
> > I saw your project on `r/rust` and I think it's a nice project.
> > The PR changes
> > 
> > * add `.DS_Store` to the `.gitignore`
> > * delete `flamegraph.svg`
> > 
> > Another thing I noticed is that when I cloned this repo, its size is `72.23 MiB`, which is quite large. Additionally, I would rename the folder `btr` to something more appropriate, like `test_files`, because I had to look through your code to understand the purpose of the directory.
> 
> Hello! Thanks for the contribution. I agree that we should have a better name like `test_files`. Do you want to include this in your PR?

I believe the branch associated with this PR should be rebased from the current `master` branch to incorporate changes from commit b9d1b1110481ae9eb0665be5f41f29be7aebd067. I'm uncertain if the directory renaming might cause a merge conflict, and this would help avoid potential issues.

**Comment by gabrieldemian** [comment]
> > > And another thing are the two worklow files in `src/.github/workflows`. Does github really run them? Because it's not quit clear from the official [documentation](https://docs.github.com/en/actions/using-workflows/about-workflows)
> > > > GitHub Actions uses YAML syntax to define the workflow. Each workflow is stored as a separate YAML file in your code repository, in a directory named .github/workflows.
> > 
> > 
> > yes, one workflow will run automated tests when pushing code, the other one will compile the binary to multiple different OS
> 
> You have duplicated your workflow files. They are present in both `./src/.github/workflows` and `./.github/workflows`. However, GitHub only recognizes the configuration from `./.github/workflows`. If you go to the "Actions" tab, you'll notice only two workflows listed instead of four.
> 
> To print all `.yml` files to the terminal:
> 
> ```shell
> $ find . | grep "\.yml$"
> ./.github/workflows/release.yml
> ./.github/workflows/build.yml
> ./src/.github/workflows/release.yml
> ./src/.github/workflows/build.yml
> ```

oh i see, i didn't notice this before! thanks

**Pull request merged**
